DELETE FROM USR_CAR;
DELETE FROM USR_USERLOGINS;
DELETE FROM USR;
DELETE FROM CAR;
DELETE FROM CARMANUFACTURER;
DELETE FROM USERLOGINS;

INSERT INTO USERLOGINS (id) VALUES (1);
INSERT INTO CARMANUFACTURER (id) VALUES (1);
INSERT INTO USR (id) VALUES (1); 
INSERT INTO CAR (id,  manufacturer_id, licenseplate) VALUES (1, 1, 'HIBERNATE');
INSERT INTO USR_CAR (user_id, cars_id) VALUES (1, 1);
INSERT INTO USR_USERLOGINS (user_id, logins_id) VALUES (1, 1);